# Generated by Django 6.0.4 on 2026-04-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("diametre", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("neuve", "Neuve"), ("occasion", "Occasion")],
                        max_length=10,
                    ),
                ),
                ("prix_achat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_vente", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite_stock", models.IntegerField(default=0)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="roues/")),
            ],
        ),
    ]
