# Generated by Django 6.0.4 on 2026-04-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntreeStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_achat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_entree", models.DateTimeField(auto_now_add=True)),
                (
                    "roue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrees",
                        to="roues.roue",
                    ),
                ),
            ],
        ),
    ]
