# Generated by Django 6.0.4 on 2026-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roues", "0004_entreestock_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteitem",
            name="benefice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="roue",
            name="prix_achat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
